public class ContactWrapper {
    
    public String Alpha_Name { get; set; }
    //public String Search_Type { get; set; }
    public String Business_Unit { get; set; }
    public String Billing_Address_1 { get; set; }
    public String Billing_Address_2 { get; set; }
    public String Billing_Address_3 { get; set; }
    public String Billing_Address_4 { get; set; }
    public String Billing_City { get; set; }
    public String Billing_State { get; set; }
    public String Billing_Country {get; set;}
    public String Billing_Postal_Code { get; set; }
    public String Division { get; set; }
    public String DOM_or_EXP { get; set; }
    public String Customer_Type { get; set; }
    public String Equipment_Customer_Type { get; set; }
    public String Address_Number { get; set; }
    
    //public String Category_Code_15 { get; set; }
    //public String Payment_Instrument { get; set; }
    public String Credit_Limit { get; set; }
    //public String Billing_Address_Type { get; set; }
    //public String Related_Address_Number { get; set; }
    public String Adjustment_Schedule { get; set; }
    public String Customer_Price_Group { get; set; }
    //public String Sold_Bill_To { get; set; }
    
    
    public String Phone_Number { get; set; }
    public String Electronic_Address_Type { get; set; }
    public String Electronic_Address { get; set; }
    //public String Messaging_Indicator { get; set; }
    //public String Electronic_Address_Category { get; set; }
    public String Contact_Information { get; set; }
    public String Payment_Terms { get; set; }
    public String Account_id{get; set;}
    public String Shipping_Address_1 { get; set; }
    public String Shipping_Address_2 { get; set; }
    public String Shipping_Address_3 { get; set; }
    public String Shipping_Address_4 { get; set; }
    public String Shipping_City { get; set; }
    public String Shipping_State { get; set; }
    public String Shipping_Postal_Code { get; set; }
    public String Shipping_Country { get; set; }
    //public String Shipping_County { get; set; }
    
    //Contact FieldMappings.
    public String First_Name { get; set; }
    public String Last_Name { get; set; }
    public String Middle_Name { get; set; }
    public String Contact_id { get; set; }
    public String Contact_Address_1 { get; set; }
    public String Contact_Address_2 { get; set; }
    public String Contact_Address_3 { get; set; }
    public String Contact_Address_4 { get; set; }
    public String Contact_City { get; set; }
    public String Contact_State { get; set; }
    public String Contact_Postal_Code { get; set; }
    public String Contact_Country { get; set; }
    public String Contact_Email { get; set; }
    public String Contact_Title { get; set; }
    public String Contact_Phone_Number { get; set; }
    //public String Contact_Type_Code { get; set; }
    
    public String Contact_Alpha_Name { get; set; }
    
    
    
    public ContactWrapper() {}
    
}